#!/usr/bin/python

import sys

from todotxt import todotxt

todotxt = todotxt()

commands = {'due', 'prjs', 'do', 'ls', 'add', 'done', 'update'}

if ( len(sys.argv) > 1 and sys.argv[1] in commands ):
    if ( sys.argv[1] == 'due' ):
        if ( len(sys.argv) > 2 ):
            todotxt.show_dues(' '.join(sys.argv[2:]))
        else:
            todotxt.show_dues()
    elif ( sys.argv[1] == 'prjs' ):
        prjs = None
        operator = None
        if ( len(sys.argv) > 2 ):
            prjs = set()
            for prj in range(2, len(sys.argv)):
                prjs.add(sys.argv[prj])
            operator = 'union'
        todotxt.show_prjs(prjs, operator)
    elif ( sys.argv[1] == 'do' ):
        todotxt.do_sth(sys.argv[2]) 
    elif ( sys.argv[1] == 'ls' ):
        todotxt.show_tasks()
    elif ( sys.argv[1] == 'add' ):
        task = ''
        for i in range(2, len(sys.argv)):
            task += sys.argv[i]+' '
        todotxt.add_task(task)
    elif ( sys.argv[1] == 'done' ):
        todotxt.show_done()
    elif ( sys.argv[1] == 'update' ):
        print 'Not implemented yet'
else:
    print 'Available commands are:'
    for command in commands:
        print command
